# Generated by Django 2.2.6 on 2019-11-15 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midcityapp', '0003_auto_20191114_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers_required',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
