# Generated by Django 2.2.6 on 2019-11-30 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midcityapp', '0004_auto_20191115_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myvolunteerships', to='accounts.User'),
        ),
    ]
